### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by FreeTymeKiyan** [beyondcode/writeout.ai#7]
1. Translations could have a line saying that "This is translated using DeepL" blahblahblah
2. VTT timestamp is often messed up after translation, e.g. timestamp is goes after a line instead of being on a new line. 
3. Translation just doesn't work: I uploaded Chinese audio and got my transcript. I clicked on "change to English" when the transcript is ready. After a while, the transcript is still in Chinese. But the web page says the translation has bene done.

**Comment by mpociot** [comment]
The translation happens using the OpenAI ChatGPT API, so there isn't much we can do about it.
I'd accept a PR that modifies the behavior in some way though.

**Comment by FreeTymeKiyan** [comment]
Interesting... OpenAI ChatGPT API has a response saying "This is translated using DeepL..."?

Are you acknowledging these issues or not? If you just close them they will just be ignored.
